#!/usr/bin/env bash

source "common"

mkdir -p "${REAL_HOME}/.local/share/applications"
cat > "${REAL_HOME}/.local/share/applications/${PROGRAM_NAME}.desktop" << EOL
[Desktop Entry]
Type=Application
Version=1.0
Name="${PROGRAM_NAME}"
Comment="${PROGRAM_COMMENT}"
Path="${SCRIPT_DIR}"
Exec="${START_SCRIPT}"
Icon="${PROGRAM_ICON_PATH}"
Terminal=false
Categories=Game;
EOL
