#!/usr/bin/env bash

source "common"

install() {
  print "Installing..."
  env WINEARCH="${WINE_ARCH}" WINEPREFIX="${DATA_DIR}" "${WINE_BIN_DIR}/wine" "${1}" &>> "${LOG_FILE}"
  is_failed "Done" "Installation failed."
}

install "${1}"
