#!/usr/bin/env bash

source "common"

create_wine_prefix() {
  print "Preparing data directory"
  env WINEARCH="${WINE_ARCH}" WINEPREFIX="${DATA_DIR}" "${WINE_BIN}/wineboot" -u
}

replace_symlink_with_directory() {
  WINDOWS_USER_DIR="${DATA_DIR}/drive_c/users/${USER}"
  rm -rf "${WINDOWS_USER_DIR}/Desktop"
  rm -rf "${WINDOWS_USER_DIR}/Downloads"
  rm -rf "${WINDOWS_USER_DIR}/My Documents"
  rm -rf "${WINDOWS_USER_DIR}/My Music"
  rm -rf "${WINDOWS_USER_DIR}/My Pictures"
  rm -rf "${WINDOWS_USER_DIR}/My Videos"
  rm -rf "${WINDOWS_USER_DIR}/Templates"

  mkdir "${WINDOWS_USER_DIR}/Desktop"
  mkdir "${WINDOWS_USER_DIR}/Downloads"
  mkdir "${WINDOWS_USER_DIR}/My Documents"
  mkdir "${WINDOWS_USER_DIR}/My Music"
  mkdir "${WINDOWS_USER_DIR}/My Pictures"
  mkdir "${WINDOWS_USER_DIR}/My Videos"
  mkdir "${WINDOWS_USER_DIR}/Templates"
}

start() {
  create_wine_prefix
  replace_symlink_with_directory
}

start
