#!/usr/bin/env bash

source "common"

start_game() {
  env WINEPREFIX="${DATA_DIR}" WINEDEBUG=fps "${WINE_BIN_DIR}/wine" "${PROGRAM_EXE}" 2>&1 |\
    tee /dev/stderr | sed -u -n -e '/trace/ s/.*approx //p' |
    osd_cat --lines=1 --font="lucidasanstypewriter-bold-18" --color=yellow
}

start_program() {
  env WINEPREFIX="${DATA_DIR}" WINEDEBUG=fps "${WINE_BIN_DIR}/wine" "${PROGRAM_EXE}" &>> "${LOG_FILE}"
}

start() {
  if [[ "${1}" == "cfg" ]]; then
    print "Starting winecfg..."
    env WINEARCH="${WINE_ARCH}" WINEPREFIX="${DATA_DIR}" "${WINE_BIN_DIR}/winecfg" &>> "${LOG_FILE}"
    is_failed "Done" "Starting winecfg failed."
  elif [[ "${1}" == "winetricks" ]]; then
    print "Starting winetricks..."
    env WINEARCH="${WINE_ARCH}" WINEPREFIX="${DATA_DIR}" "${WINE_BIN_DIR}/winetricks" &>> "${LOG_FILE}"
    is_failed "Done" "Starting winetricks failed."
  elif [[ "${IS_GAME}" == "yes" ]]; then
    start_game
  else
    start_program
  fi
}

start "${1}"
