#!/usr/bin/env bash

source "common"

start_game() {
  env WINEPREFIX="${PREFIX_DIR}" WINEDEBUG=fps "${WINE_BIN_DIR}/wine" "${PROGRAM_EXE}" 2>&1 |\
    tee /dev/stderr | sed -u -n -e '/trace/ s/.*approx //p' |
    osd_cat --lines=1 --font="lucidasanstypewriter-bold-18" --color=yellow
}

start_program() {
  env WINEPREFIX="${PREFIX_DIR}" WINEDEBUG=fps "${WINE_BIN_DIR}/wine" "${PROGRAM_EXE}"
}

start() {
  if [[ "${1}" == "cfg" ]]; then
    env WINEARCH="${WINE_ARCH}" WINEPREFIX="${DATA_DIR}" "${WINE_BIN_DIR}/winecfg"
  elif [[ "${IS_GAME}" == "yes" ]]; then
    start_game
  else
    start_program
  fi
}

start "${1}"
